### ISSUE TITLE
IRC channels to be added

### ISSUE THREAD

**Issue by quimgil** [Bitergia/mediawiki-dashboard#17]
Hi, the list of MediaWiki / Wikimedia tech IRC channels can be found at http://meta.wikimedia.org/wiki/IRC/Channels#MediaWiki_and_technical

It would be great if we could have them added. Thank you!

**Comment by aklapper** [comment]
@quimgil: Superseded by https://github.com/Bitergia/mediawiki-dashboard/pull/61 and https://phabricator.wikimedia.org/T56230 ? If so feel free to close.
