### ISSUE TITLE
Zero values in Code Review

### ISSUE THREAD

**Issue by quimgil** [Bitergia/mediawiki-dashboard#20]
There are some properties with value zero at http://korma.wmflabs.org/browser/scr.html

verified: 0
approved: 0
code review: 0
Waiting for Reviewer: 0
Waiting for Submitter: 0

Suspicious. Also:

Waiting for Reviewer & Waiting for Submitter could go under New since this is where they belong.

All entries should be capitalized.

**Comment by aklapper** [comment]
@quimgil: Zero values seem to be obsolete now? At least I cannot see any... (Cannot close issues here.)
